export const SET_RECORDS = 'SET_RECORDS';
export const ADD_RECORD = 'ADD_RECORD';
export const UPDATE_RECORD = 'UPDATE_RECORD';
export const REMOVE_RECORD = 'REMOVE_RECORD';
export const LOADING_RECORDS = 'LOADING_RECORDS';
export const LOADED_RECORDS = 'LOADED_RECORDS';